title: JieTalk
description: 我的一些观点和感悟
author:
  name: JieTalk
timezone: Asia/Shanghai
permalink: /:year/:month/:title:output_ext
excerpt_separator: <!--more-->
markdown: kramdown
auto: true
server: true



# set up remote_theme
remote_theme: jekyll/minima

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"
google_analytics: UA-62508887-1
header_pages:
  - about.md

# Add to plugins: list
plugins:
  - jekyll-remote-theme

