timezone: Asia/Shanghai
permalink: /:year/:month/:title::output_ext
excerpt_separator: <!--more-->
markdown: kramdown
auto: true
server: true
google_analytics: UA-62508887-1
# set up remote_theme
remote_theme: jekyll/minima


author.name: 杰说

# Add to plugins: list
plugins:
  - jekyll-remote-theme

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %H:%M"